// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3w0emX_EiWXbUJAFBuy3isDCL48LkNN0',
    appId: '1:44570275246:web:aa4763a8701b730b4b6c3f',
    messagingSenderId: '44570275246',
    projectId: 'logitrack-app-679a4',
    authDomain: 'logitrack-app-679a4.firebaseapp.com',
    storageBucket: 'logitrack-app-679a4.firebasestorage.app',
    measurementId: 'G-TDW961Q9SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1fjxl9ybIG6vJTj4gr5Ysfh8tl1lWYhY',
    appId: '1:44570275246:android:a3344fd3e692b55e4b6c3f',
    messagingSenderId: '44570275246',
    projectId: 'logitrack-app-679a4',
    storageBucket: 'logitrack-app-679a4.firebasestorage.app',
  );
}
